### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [Key-Log-Economics/eco-valuator#12]
# Problem

Can you please change the plugin icon to something more informative.

**Comment by Gustry** [comment]
There isn't a icon, like many QGIS plugin. The one plugins.qgis.org is just the default when there is no icon provided in metadata.txt.
But I found this issue : https://github.com/Key-Log-Economics/eco-valuator/issues/13

**Comment by epurpur** [comment]
I have change the plugin icon
