### ISSUE TITLE
Do not create new plugin, just update the version

### ISSUE THREAD

**Issue by Gustry** [Key-Log-Economics/eco-valuator#13]
It seems you have already an existing plugin : https://plugins.qgis.org/plugins/ecovaluator/

Is-it normal that you are creating a new one? https://plugins.qgis.org/plugins/eco-valuator/
You should just add new version to the existing plugin  https://plugins.qgis.org/plugins/ecovaluator/, no?

**Comment by epurpur** [comment]
Thank you, I think I have fixed the problem

**Comment by Gustry** [comment]
Ok, do you mind if you/we remove https://plugins.qgis.org/plugins/eco-valuator/ ? It has a single version which won't be approved.

**Comment by epurpur** [comment]
yes, please. Thank you for following up with me about this
